import os

from dataclasses import dataclass
from google.cloud import dialogflow


@dataclass
class DialogEngineInput:
    sender = ''  # Could be a number, email, user id etc.
    input_message = '' # Could be hello/I need to book a flight etc.
    preffered_language = 'en-US'


class _BaseDialogEngine:
    def __init__(self,  request_data: DialogEngineInput) -> None:
        self._Client = None
        self._RequestData = request_data

    @staticmethod
    def _generate_session_id(hash_input:str) -> str:
        '''Generates a 32 byte hash value for any string input'''
        import hashlib
        return hashlib.sha512(bytes(hash_input, encoding='UTF-8')).hexdigest()


class TensoFlowDialogEngine(_BaseDialogEngine):
    def __init__(self, request_data: DialogEngineInput) -> None:
        super().__init__(request_data)
        self._Client = dialogflow.SessionsClient()

    def _load_session(self):
        '''Notes on dialogflow sessions:

        i. Session - represents a conversation between a Dialogflow agent and an end-use

        ii. Each session is determined unique by a session ID generated by your system

        iii. Dialogflow retains session data for 20 minutes
        '''
        session_id = self._generate_session_id(self._RequestData.sender)
        session = self._Client.session_path(os.getenv('DIALOG_FLOW_PROJ_ID'), session_id)
        return session

    def _get_response(self, user_input:str):
        session = self._load_session()
        text_input = dialogflow.TextInput(text=user_input, 
        language_code=self._RequestData.preffered_language)
        query_input = dialogflow.QueryInput(text=text_input)
        response = self._Client.detect_intent(session=session, query_input=query_input)
        return response.query_result.fulfillment_text

    def execute(self):
        fullfillment = self._get_response(self._RequestData.input_message)
        return fullfillment


def _main():
    # FOR TESTING ONLY!
    input = DialogEngineInput()
    input.input_message = 'Hi I need to rent a car'
    input.sender = '123456789'
    engine = TensoFlowDialogEngine(request_data=input)
    botresponse = engine.execute()
    print('BOT RESPONDED WITH: \n', botresponse)

if __name__ ==  '__main__':
    _main()
